apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  url: http://prometheus1:9090/prometheus
  isDefault: true
  access: proxy
  editable: true
  basicAuth: true
  basicAuthUser: voedger
  secureJsonData:
     basicAuthPassword: voedger