global:
  scrape_interval:     30s # By default, scrape targets every 1 minute.
  evaluation_interval: 30s # By default, evaluate rules every 1 minute.
  external_labels:
     node: {{.Label}}  # mon1 for example. Use label as node.label.type in swarm
  #scrape_timeout:     10s # By default, a scrape request times out in 10 seconds.
  
# Alertmanager configuration
alerting:
  alert_relabel_configs:
    - source_labels: [node]
      regex: (.+)\d+
      target_label: node
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager1:9093 
            - alertmanager2:9093 
            - alertmanager3:9093 

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "alert.rules"

  # Configuring Prometheus to monitor itself - https://prometheus.io/docs/prometheus/latest/getting_started/
scrape_configs:
  - job_name: 'prometheus'
    # Override the global values and scrape targets for this job every 10 seconds.
    scrape_interval: 10s
    static_configs:
      # Execute query expressions prometheus_abc_xyz
      - targets: 
        - localhost:9090

  - job_name: 'node-exporter'
    scrape_interval: 10s
    static_configs:
      # node-exporter:9100 where node-exporter is service name in docker-compose.yml 
      # Execute non-prometheus_abc_xyz query expressions, e.g., node_load1 etc.
      - targets: 
        - node-1:9500
        - node-2:9500
        - node-3:9500

  - job_name: 'scylla-cluster'
    scrape_interval: 10s
    static_configs:
      # Monitor scylla nodes with embedded scylla exporter
      - targets: 
        - node-1:9180
        - node-2:9180
        - node-3:9180

  - job_name: 'cadvisor'
    scrape_interval: 10s
    static_configs:
      # Monitor swarm nodes and services
      - targets: 
        - cadvisor1:8080
        - cadvisor2:8080
        - cadvisor3:8080
        
  - job_name: 'voedger'
    scrape_interval: 10s
    static_configs:
      - targets:
        - vvm1:8000
        - vvm2:8000
        - vvm3:8000
        - vvm4:8000
        - vvm5:8000
        - vvm6:8000
