version: '3.8'

services:

  nginx:
    image: nginx:1.26.2
    depends_on:
      - vvm1
      - vvm2
      - vvm3
      - vvm4
      - vvm5
      - vvm6
    ports:
      - "80:80"
      - "443:443"
    networks:
      - voedger_net
    volumes:
      - ~/nginx:/etc/nginx/
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.AppNode1 == true
  
  vvm1:
    image: voedger/voedger:0.0.1-alpha
    networks:
      - voedger_net
    volumes:
      - /etc/hosts:/etc/hosts
    environment:
      - VOEDGER_HTTP_PORT=${VOEDGER_HTTP_PORT}
      - VOEDGER_ACME_DOMAINS=${VOEDGER_ACME_DOMAINS}
    deploy:
      restart_policy:
        condition: any
      replicas: 1
      endpoint_mode: vip
      placement:
        preferences:
          - spread: node.id
        constraints:
          - node.labels.AppNode1 == true

  vvm2:
    image: voedger/voedger:0.0.1-alpha
    networks:
      - voedger_net
    volumes:
      - /etc/hosts:/etc/hosts
    environment:
      - VOEDGER_HTTP_PORT=${VOEDGER_HTTP_PORT}
      - VOEDGER_ACME_DOMAINS=${VOEDGER_ACME_DOMAINS}
    deploy:
      restart_policy:
        condition: any
      replicas: 1
      endpoint_mode: vip
      placement:
        preferences:
          - spread: node.id

  vvm3:
    image: voedger/voedger:0.0.1-alpha
    networks:
      - voedger_net
    volumes:
      - /etc/hosts:/etc/hosts
    environment:
      - VOEDGER_HTTP_PORT=${VOEDGER_HTTP_PORT}
      - VOEDGER_ACME_DOMAINS=${VOEDGER_ACME_DOMAINS}
    deploy:
      restart_policy:
        condition: any
      replicas: 1
      endpoint_mode: vip
      placement:
        preferences:
          - spread: node.id

  vvm4:
    image: voedger/voedger:0.0.1-alpha
    networks:
      - voedger_net
    volumes:
      - /etc/hosts:/etc/hosts
    environment:
      - VOEDGER_HTTP_PORT=${VOEDGER_HTTP_PORT}
      - VOEDGER_ACME_DOMAINS=${VOEDGER_ACME_DOMAINS}
    deploy:
      restart_policy:
        condition: any
      replicas: 1
      endpoint_mode: vip
      placement:
        preferences:
          - spread: node.id


  vvm5:
    image: voedger/voedger:0.0.1-alpha
    networks:
      - voedger_net
    volumes:
      - /etc/hosts:/etc/hosts
    environment:
      - VOEDGER_HTTP_PORT=${VOEDGER_HTTP_PORT}
      - VOEDGER_ACME_DOMAINS=${VOEDGER_ACME_DOMAINS}
    deploy:
      restart_policy:
        condition: any
      replicas: 1
      endpoint_mode: vip
      placement:
        preferences:
          - spread: node.id

  vvm6:
    image: voedger/voedger:0.0.1-alpha
    networks:
      - voedger_net
    volumes:
      - /etc/hosts:/etc/hosts
    environment:
      - VOEDGER_HTTP_PORT=${VOEDGER_HTTP_PORT}
      - VOEDGER_ACME_DOMAINS=${VOEDGER_ACME_DOMAINS}
    deploy:
      restart_policy:
        condition: any
      replicas: 1
      endpoint_mode: vip
      placement:
        preferences:
          - spread: node.id


networks:
  voedger_net:
    external: true
